config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

# resources :contacts

resources :projects do
  resources :contacts
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  include Redmine::SafeAttributes

  belongs_to :user
  belongs_to :project

  attr_protected :id
  # attr_accessible :custom_field_values, :name, :author_id, :about, :custom_fields, :project_id

  acts_as_customizable

  acts_as_attachable

  acts_as_event :datetime => :updated_at,
                :description => :about,
                :title => Proc.new { |o| "#{l(:label_title_contacts)} ##{o.id} - #{o.name}" },
                :url => Proc.new { |o| { :controller => 'contacts', :action => 'show', :id => o.id, :project_id => o.project_id } }

  acts_as_searchable :columns => [ "#{table_name}.about", "#{table_name}.name" ],
                     :scope => joins(:project),
                     :date_column => :created_at


  safe_attributes 'name',
                  'author_id',
                  'project_id',
                  'about',
                  'custom_field_values',
                  'custom_fields'


end

app/models/contact_custom_field.rb
class ContactCustomField < CustomField
  def type_name
    l(:contact)
  end
end

app/models/contact_query.rb
class ContactQuery < Query

  self.queried_class = Contact

  self.available_columns = [
      QueryColumn.new(:id, :sortable => "#{Contact.table_name}.id", :default_order => 'desc', :caption => 'Fields'),
      QueryColumn.new(:project, :sortable => "#{Project.table_name}.name", :groupable => true),
      QueryColumn.new(:about, :sortable => "#{Contact.table_name}.about"),
      QueryColumn.new(:name, :sortable => "#{Contact.table_name}.name"),
  ]



  def initialize_available_filters
    add_available_filter "spent_on", :type => :date_past
    add_available_filter "about", :type => :text
    add_custom_fields_filters(ContactCustomField)
    add_associations_custom_fields_filters :project
  end



  def available_columns
    return @available_columns if @available_columns
    @available_columns = self.class.available_columns.dup
    @available_columns += ContactCustomField.visible.
        map {|cf| QueryCustomFieldColumn.new(cf) }
    @available_columns
  end

  def contact_count_by_group
    grouped_query do |scope|
      scope.count
    end
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  rescue_from Query::StatementInvalid, :with => :query_statement_invalid

  helper :custom_fields
  include CustomFieldsHelper
  helper :queries
  include QueriesHelper
  helper :sort
  include SortHelper
  helper :issues
  include IssuesHelper

  before_filter :find_project_by_project_id, :only => [:index, :create, :edit, :update, :new, :destroy]
  before_filter :set_contacts, :only => [:update, :edit, :destroy, :show]


  def index
    @query = ContactQuery.build_from_params(params, :name => '_')
    sort_init(@query.sort_criteria.empty? ? [['spent_on', 'desc']] : @query.sort_criteria)
    sort_update(@query.sortable_columns)


    @contacts = Contact.where(project_id: @project.id)

    @contact_count_by_group = @query.contact_count_by_group

  end

  def show
  end

  def new
    @contact = Contact.new()
    @contact.safe_attributes = params[:contact]
  end

  def edit
  end

  def create
    @contact = Contact.new

    @contact.safe_attributes = params[:contact]
    #@contact = Contact.new(contact_params)

    @contact.save_attachments(params[:attachments])
    render_attachment_warning_if_needed(@contact)

    @contact.author_id = User.current.id
    @contact.project_id = @project.id

    respond_to do |format|

      if @contact.save

        format.html { redirect_to :controller => 'contacts', :action => 'index', :project_id => @project.id }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @contact.safe_attributes = params[:contact]
    respond_to do |format|
      @contact.save_attachments(params[:attachments])
      render_attachment_warning_if_needed(@contact)

      @contact.project_id = @project.id

      if @contact.save
        format.html { redirect_to :controller => 'contacts', :action => 'index', :project_id => @project.id }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to :controller => 'contacts', :action => 'index', :project_id => @project.id }
    end
  end

  private

  # def contact_params
  #   params.require(:contact).permit(:name, :author_id, :project_id, :about)
  # end

  def set_contacts
    @contact = Contact.find(params[:id])
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for([ @project, @contact]) do |f| %>


    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :about %><br>
      <%= f.text_field :about %>
    </div>



    <% custom_field_values = @contact.custom_field_values %>
    <% if custom_field_values.present? %>
        <div class="splitcontent">
          <div class="splitcontentleft">
            <% i = 0 %>
            <% split_on = (custom_field_values.size / 2.0).ceil - 1 %>
            <% custom_field_values.each do |value| %>
                <p><%= custom_field_tag_with_label :contact, value %></p>
                <% if i == split_on -%>
                    </div><div class="splitcontentright">
                <% end -%>
                <% i += 1 -%>
            <% end -%>
            </div>
            </div>
    <% end %>


    <div class="box">
      <p>
        <label><%= l(:label_attachment_plural) %></label>
        <%= render :partial => 'attachments/form' %>
      </p>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

<% end %>

app/views/contacts/_list.html.erb
<%= form_tag({}) do -%>
    <%= hidden_field_tag 'back_url', url_for(params), :id => nil %>
    <div class="autoscroll">
      <table class="list issues <%= sort_css_classes %>">
        <thead>
        <tr>
          <th class="checkbox hide-when-print">
            <%= check_box_tag 'check_all', '', false, :class => 'toggle-selection',
                              :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
          </th>
          <% query.inline_columns.each do |column| %>
              <%= column_header(column) %>
          <% end %>
        </tr>
        </thead>
        <tbody>
        <% grouped_issue_list(contacts, @query, @contact_count_by_group) do |contact, level, group_name, group_count, group_totals| -%>
            <% if group_name %>
                <% reset_cycle %>
                <tr class="group open">
                  <td colspan="<%= query.inline_columns.size + 1 %>">
                    <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
                    <span class="name"><%= group_name %></span> <span class="count"><%= group_count %></span> <span class="totals"><%= group_totals %></span>
                    <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}",
                                         "toggleAllRowGroups(this)", :class => 'toggle-all') %>
                  </td>
                </tr>
            <% end %>
            <tr id="contact-<%= contact.id %>" class="hascontextmenu <%= cycle('odd', 'even') %> <%= level > 0 ? "idnt idnt-#{level}" : nil %>">
              <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", contact.id, false, :id => nil) %></td>
              <%= raw query.inline_columns.map {|column| "<td>#{column_content(column, contact)}</td>"}.join %>
            </tr>
            <% @query.block_columns.each do |column|
              if (text = column_content(column, contact)) && text.present? -%>
                    <tr class="<%= current_cycle %>">
                      <td colspan="<%= @query.inline_columns.size + 1 %>"><%= text %></td>
                    </tr>
                <% end -%>
            <% end -%>
        <% end -%>
        </tbody>
      </table>
    </div>
<% end -%>

app/views/contacts/edit.html.erb
<%= render 'form' %>

app/views/contacts/index.html.erb
<div class="contextual">
<%= link_to l(:add_contact), new_project_contact_path(project_id: @project.id), class: 'icon icon-add' %>
</div>

<h2>Contacts</h2>

<%= form_tag({ :controller => 'contacts', :action => 'index', :project_id => @project },
             :method => :get, :id => 'query_form') do %>
<div id="query_form_with_buttons" class="hide-when-print">
  <%= hidden_field_tag 'set_filter', '1' %>
  <div id="query_form_content">
<fieldset id="options" class="collapsible collapsed">
  <legend onclick="toggleFieldset(this);"><%= l(:label_options) %></legend>
  <div style="display: none;">
    <table>
      <tr>
        <td class="field"><%= l(:field_column_names) %></td>
        <td><%= render_query_columns_selection(@query) %></td>
      </tr>
      <tr>
        <td class="field"><label for='group_by'><%= l(:field_group_by) %></label></td>
        <td><%= select_tag('group_by',
                           options_for_select(
                               [[]] + @query.groupable_columns.collect {|c| [c.caption, c.name.to_s]},
                               @query.group_by)
                ) %></td>
      </tr>
      <tr>
        <td class="field"><%= l(:button_show) %></td>
        <td><%= available_block_columns_tags(@query) %></td>
      </tr>
      <tr>
        <td><%= l(:label_total_plural) %></td>
        <td><%= available_totalable_columns_tags(@query) %></td>
      </tr>
    </table>
  </div>
</fieldset>
    </div>

<p class="buttons">
  <%= link_to_function l(:button_apply), '$("#query_form").submit()', :class => 'icon icon-checked' %>
  <%= link_to l(:button_clear), { :set_filter => 1, :project_id => @project }, :class => 'icon icon-reload'  %>
  <% if @query.new_record? %>
      <% if User.current.allowed_to?(:save_queries, @project, :global => true) %>
          <%= link_to_function l(:button_save),
                               "$('#query_form').attr('action', '#{ @project ? new_project_query_path(@project) : new_query_path }').submit()",
                               :class => 'icon icon-save' %>
      <% end %>
  <% else %>
      <% if @query.editable_by?(User.current) %>
          <%= link_to l(:button_edit), edit_query_path(@query), :class => 'icon icon-edit' %>
          <%= delete_link query_path(@query) %>
      <% end %>
  <% end %>
</p>
</div>
<% end %>

<% if @contacts.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
    <%= render_query_totals(@query) %>
    <%= render :partial => 'contacts/list', :locals => {:contacts => @contacts, :query => @query} %>
<% end %>


--------------------------------------------------------------------------------------------------------------
<% @contacts.each do |contact| %>
    <p>
      <%= contact.name %>
      <%= contact.about %>
      <%= contact.project %>

      <% contact.custom_values.each do |custom_value| %>
          <% if !custom_value.value.blank? %>
            <li><%= custom_value.custom_field.name%>: <%=h show_value(custom_value) %></li>
        <% end %>
    <% end %>

      <%= render :partial => 'attachments/links',
      :locals  => { :attachments => contact.attachments,
      :options => { :deletable => User.current.logged? }
      } %>

    <td><%= link_to l(:edit), edit_project_contact_path(@project, contact), class: 'icon icon-edit' %></td>
    <td><%= link_to l(:delete), [@project, contact], method: :delete, data: { confirm: l(:are_you_sure) }, class: 'icon icon-del' %></td>
    </p>
<% end %>

app/views/contacts/new.html.erb
<%= render 'form' %>